# .streamlit/secrets.toml

SUPABASE_URL = "https://ophypahgfhhknircimab.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9waHlwYWhnZmhoa25pcmNpbWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzU3MjksImV4cCI6MjA2NTE1MTcyOX0.wi_ytU9pa4TW1cWKI1l4rz7o4stCU0kP4KBDJ_F-9r4"